### PR TITLE
Gitab CI example. Tests, delivering artifacts.

### PR DESCRIPTION
**Pull request by vindarel**
Hello,

a simple example for Gitlab CI. 

Cheers !

ps: we miss you ;)

### CODE REVIEW

**Comment by vindarel** [comment]
Note that it is published on the Cookbook (https://lispcookbook.github.io/cl-cookbook/testing.html#gitlab-ci), and that I can rebase.

**Comment by eudoxia0** [comment]
Is this ready to go? Additionally, are there licensing problems with putting this here in addition to the cookbook?

>ps: we miss you ;)

Thank you for the kind words.

**Comment by vindarel** [comment]
I rebased, it is ready now.

Not sure about the licence. Here's the Cookbook one https://lispcookbook.github.io/cl-cookbook/license.html. It implies to add a disclaimer. I am the author on both sides, hope that makes it simpler.

**Comment by eudoxia0** [comment]
If you are the author and because the Cookbook has a fairly permissive license, I don't think it will be a problem. Still, can you add a link from the post to the section on the cookbook containing the original guide?

**Comment by eudoxia0** [comment]
Thank you

**Pull request merged**
